name = "ConstitutiveModels"
uuid = "fc6ee7eb-129a-416f-804b-d7271ece6a3a"
authors = ["Craig M. Hamel <cmhamel32@gmail.com> and contributors"]
version = "0.3.1"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
InverseLangevinApproximations = "b82787f2-62be-403e-9078-6d9feafd7ee3"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Tensors = "48a634ad-e948-5137-8d70-aa71f2a747f4"

[weakdeps]
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[extensions]
ConstitutiveModelsRecipesBaseExt = ["LaTeXStrings", "RecipesBase"]

[compat]
Aqua = "0.8"
DocStringExtensions = "0.9"
ForwardDiff = "1"
InverseLangevinApproximations = "0.2"
LaTeXStrings = "1"
RecipesBase = "1"
Roots = "2"
StaticArrays = "1"
Tensors = "1"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
